version: '3'

services:
  server:
    container_name: glam-server
    build: .
    ports:
      - 8000:8000
    restart: always
    environment:
      - DATABASE=mongodb://host.docker.internal:27017
      - PORT=8000
      - BRAINTREE_MERCHANT_ID=3wv8zr3vrx5y2h8b
      - BRAINTREE_PUBLIC_KEY=sd25mjxk4hhw9t7r
      - BRAINTREE_PRIVATE_KEY=a5df57ceeb3919851d4cd2f8c51db3a5
