version: '3'

services:
  server:
    container_name: glam-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app/public/uploads:/usr/src/app/public/uploads
    ports:
      - 80:80
    env_file:
      - .env
    restart: always

# testing CICD