version: '3'

services:
  server:
    container_name: glam-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    env_file:
      - .env
    restart: always

# testing CICD pipeline after terraform updates, testing 7:50pm 3rd April